### PR TITLE
Minor fixes and improvements on settings

### LINKED ISSUE #439: [Bug] Buttons cannot be remapped after removing a controller outside of the game.
**Describe the bug**
Input cannot be remapped after removing controller outside of the game

**To Reproduce**
1. Attach two controllers that USC can recognize
2. Launch game, map every button to a controller
3. Close game
4. Disconnect a controller
5. Restart game
6. Go back to settings and remap a button

**Expected behavior**
Prompt to remap button or knob

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10 Education 20H2
 - GPU: GeForce RTX 2060 Super
 - CPU: Ryzen 5 3600
 - Version: 0.4.0, Git commit 2021-02-28_e76cb5b0
 
**Additional Information**
- The bug also stops the user from using the controller to navigate the menu.
- Used a DualShock 4  + DS4 Windows along with a Yuancon to reproduce the issue, but this can most likely be reproducible with any two sets of controllers.

**Log file**
```
[13:08:26][Info] Starting task "Application Setup"
[13:08:26][Info] Version: 0.4.0
[13:08:26][Info] Git commit: 2021-02-28_e76cb5b0
[13:08:26][Info] The locale was changed from C to English_Canada.utf8
[13:08:26][Info] Starting task "Font library initialization"
[13:08:26][Info] Finished task "Font library initialization" in  5 ms
[13:08:26][Info] Starting task "Creating Window"
[13:08:27][Info] Listing 1 Joysticks:
[13:08:27][Info] [0] "YuanCon" (16 buttons, 2 axes, 0 hats)
[13:08:27][Info] Finished task "Creating Window" in  299 ms
[13:08:27][Error] Out of range controller [1], number of available controllers is 1
[13:08:27][Info] Starting task "Audio Init"
[13:08:27][Info] Finished task "Audio Init" in  34 ms
[13:08:27][Info] Starting task "GL Init"
[13:08:27][Info] OpenGL Version: 3.3.0 NVIDIA 461.09
[13:08:27][Info] OpenGL Shading Language Version: 3.30 NVIDIA via Cg compiler
[13:08:27][Info] OpenGL Renderer: GeForce RTX 2060 SUPER/PCIe/SSE2
[13:08:27][Info] OpenGL Vendor: NVIDIA Corporation
[13:08:27][Info] Finished task "GL Init" in  21 ms
[13:08:27][Info] Starting task "Discord RPC Init"
[13:08:27][Info] Starting task "Check for updates"
[13:08:27][Info] Finished task "Discord RPC Init" in  0 ms
[13:08:27][Info] Starting task "Load Transition Screens"
[13:08:27][Info] Finished task "Load Transition Screens" in  49 ms
[13:08:27][Normal] Update check status code: 200
[13:08:32][Error] Failed to open joystick 1
[13:08:32][Error] Failed to open gamepad: 1
[13:10:14][Error] Failed to add IApplicationTickable
[13:10:16][Error] Failed to open joystick 1
[13:10:16][Error] Failed to open gamepad: 1
[13:10:18][Error] Failed to add IApplicationTickable
[13:10:24][Error] Failed to open joystick 1
[13:10:24][Error] Failed to open gamepad: 1
[13:10:26][Error] Failed to add IApplicationTickable
[13:10:37][Error] Failed to open joystick 1
[13:10:37][Error] Failed to open gamepad: 1
[13:10:39][Error] Failed to add IApplicationTickable
[13:10:45][Error] Failed to open joystick 1
[13:10:45][Error] Failed to open gamepad: 1
[13:10:47][Error] Failed to add IApplicationTickable
[13:13:37][Error] Out of range controller [1], number of available controllers is 1
[13:13:37][Normal] Update check status code: 200

```

### PR DESCRIPTION
**Pull request by 123jimin**
- Color settings and enum settings made sure not to be clipped because of insufficient scroll area
- Previously hidden fullscreen setting added to settings page
- Game window position now saved
- Window outside of monitor display region now fixed according to the setting `AdjustWindowPositionOnStartup` (on by default)
    - It works a little bit annoyingly when the window was maximized before, due to different border size, but otherwise works fine.
    - The annoying behavior is not a regression (same thing happens on `master` branch of USC)
- Settings renaming and relocations
    - "Display" renamed to "Visual" to reduce confusion between it with systems graphic settings
    - Offset settings moved from "Input" to "Game"
    - Other minor movements
- Out-of-bounds enum settings now shown to be out-of-bound (also related to the next fix)
- Fixes #439: slightly more detailed error messages
- When binding controller buttons, the escape key will cancel the binding. (It's unfortunate that the same can't be done for keyboard key binding screen...)
- Adjusted font baking algorithm so that required texture size for fallback font is reduced (32768 to 8192)
    - Any GPU supporting DirectX 10 should be able to bake the font texture now.
    - Partial baking support: if supported texture size is not big enough, only hiragana/katakana characters are baked.
        - This requires only 1024 x 1024 px texture support; any device supporting OpenGL ES 3.0 should be able to handle this.
- Same for multiplayer chat, but partial baking is not supported (not a big problem as required texture size is still reduced)

### CODE REVIEW

File: Graphics/src/Window.cpp [hunk 1]
```diff
@@ -374,61 +404,182 @@ namespace Graphics
...
+							}
+						}
+					}
+
+					if (foundContained)
+					{
+						break;
+					}
+
+					// Optimally, this should be set to the largest rectangle inside `bounds intersect windowRect`.
```
Comment (123jimin) [inline Graphics/src/Window.cpp:556]: ... but I didn't...
